### ISSUE TITLE
Is this still the source for framework-zephyr?

### ISSUE THREAD

**Issue by sur5r** [platformio/zephyr#3]
I was trying to modify the zephyr tree in my platformio project but was unable to find a git repo or commit corresponding to e.g. http://dl.platformio.org/packages/framework-zephyr-2.20200.200401.tar.gz

So I'm wondering how framework-zephyr is maintained.

**Comment by martinjaeger** [comment]
As far as I understand, the PlatformIO build scripts are added to this repository after a new Zephyr release and afterwards the `platform.json` in the platform repository (e.g. `platform-ststm32`) has to be updated to point towards the new branch.

I see that in order to support a new version of Zephyr also the boards and examples have to be updated (as done [here](https://github.com/platformio/platform-ststm32/commit/a406bacb03f805e250e07f66362c703d605c71f8)). 

@valeros I am wondering if it would make sense to add the platformio build scripts to upstream Zephyr repository so that it is easier to upgrade PlatformIO to a new Zephyr release. Or does it require manual intervention to add the Zephyr modules (from `west.yml`) to `platform.json` anyway?

**Comment by valeros** [comment]
> I see that in order to support a new version of Zephyr also the boards and examples have to be updated

> Or does it require manual intervention to add the Zephyr modules (from west.yml) to platform.json anyway?

That's right, besides shipping specific versions of Zephyr modules, each new Zephyr release requires some preparation on our side (mainly because CMake doesn't export exhaustive info we need).

**Comment by martinjaeger** [comment]
> That's right, besides shipping specific versions of Zephyr modules, each new Zephyr release requires some preparation on our side (mainly because CMake doesn't export exhaustive info we need).

Ok, thanks for the quick answer. In that case there doesn't seem to be a simple way to implement more automatic updates.

**Comment by martinjaeger** [comment]
@valeros I'm wondering how Zephyr v2.5 was integrated into `ststm32@~12.0.0`, as this repo is not updated anymore.

I'm asking because I'm maintaining [my own Zephyr fork](https://github.com/LibreSolar/zephyr) with some cherry-picked PRs which did not make it into Zephyr upstream yet. Previously I cherry-picked your commits added to this repo and pointed PlatformIO to the forked repo in `platformio.ini`. Is this process still possible and can you tell me where to find the repo PlatformIO uses as a basis? Or did you even change the build system such that the PlatformIO python scripts are not necessary in the Zephyr repo anymore? Would be glad to get some more insights how this works :)

**Comment by valeros** [comment]
Thanks for bringing it up, now v2.5 is the default branch with updated PlatformIO build scripts.
