### ISSUE TITLE
Update to zephyr 2.6

### ISSUE THREAD

**Issue by tclarke** [platformio/zephyr#8]
The latest zephyr is 2.6. Platformio should be upgraded to support this.

**Comment by cpavot** [comment]
Hello, I'm interested in this version. Do you have any ETA ? Thanks!

**Comment by valeros** [comment]
Hi, support for the latest Zephyr 2.6 was added to all available platforms a week ago https://piolabs.com/blog/news/platformio-oss-july-2021-updates.html

**Comment by cpavot** [comment]
Hi @valeros, thanks a lot. I'm currently installing latest nordic platform version and zephyr framework v2.6.
Still one question. Are you still using https://github.com/platformio/zephyr ? 
I did not see any v2.6 branch in this repo. As I have some patches to be ported on top of zephyr framework, I'm wondering if the strategy to integrate zephyr in platformio has been changed. Thanks!

**Comment by martinjaeger** [comment]
I would also really appreciate to be able to have a transparent way to use a forked repo of Zephyr that I can use in PlatformIO so that some patches can be cherry-picked before the next release comes out.

Ideally, even the vanilla Zephyr repo would become compatible with PlatformIO by upstreaming the custom PlatformIO scripts :)

**Comment by cpavot** [comment]
> Ideally, even the vanilla Zephyr repo would become compatible with PlatformIO by upstreaming the custom PlatformIO scripts

I was wondering if this was the new strategy in place, but I checked and that's not the case... So where is the platformio zephyr v2.6 integration branch ? Last commit in https://github.com/platformio/zephyr is from March 9th...
